"""
API Keys Setup Script
Helps users set up their OpenAI and GROQ API keys for the teaching assistant application.
"""

import os
import sys

def setup_api_keys():
    """Interactive setup for API keys"""

    print("=" * 60)
    print("[KEY] Teaching Assistant - API Keys Setup")
    print("=" * 60)
    print()

    # Check if .env file exists
    env_file = ".env"
    env_exists = os.path.exists(env_file)

    if env_exists:
        print(f"[FOUND] Found existing {env_file} file")
    else:
        print(f"[INFO] Creating new {env_file} file")

    # Load existing environment variables if .env exists
    existing_vars = {}
    if env_exists:
        try:
            with open(env_file, 'r') as f:
                for line in f:
                    if '=' in line and not line.strip().startswith('#'):
                        key, value = line.strip().split('=', 1)
                        existing_vars[key] = value
        except Exception as e:
            print(f"Warning: Error reading existing .env file: {e}")

    print()
    print("[SETUP] Setting up API Keys:")
    print()

    # OpenAI API Key
    print("1. OpenAI API Key (for Speech-to-Text and Text-to-Speech)")
    print("   Get your key from: https://platform.openai.com/api-keys")
    current_openai = existing_vars.get('OPENAI_API_KEY', '')
    if current_openai and current_openai != 'your_openai_api_key_here':
        print(f"   Current key: {current_openai[:10]}...{current_openai[-10:]}")
        use_existing = input("   Keep existing key? (y/n): ").lower().strip()
        if use_existing == 'y':
            openai_key = current_openai
        else:
            openai_key = input("   Enter your OpenAI API key: ").strip()
    else:
        openai_key = input("   Enter your OpenAI API key: ").strip()

    print()

    # GROQ API Key
    print("2. GROQ API Key (for Language Model)")
    print("   Get your key from: https://console.groq.com/keys")
    current_groq = existing_vars.get('GROQ_API_KEY', '')
    if current_groq and current_groq != 'your_groq_api_key_here':
        print(f"   Current key: {current_groq[:10]}...{current_groq[-10:]}")
        use_existing = input("   Keep existing key? (y/n): ").lower().strip()
        if use_existing == 'y':
            groq_key = current_groq
        else:
            groq_key = input("   Enter your GROQ API key: ").strip()
    else:
        groq_key = input("   Enter your GROQ API key: ").strip()

    # Validate keys
    if not openai_key or openai_key == 'your_openai_api_key_here':
        print("[ERROR] OpenAI API key is required for speech services!")
        return False

    if not groq_key or groq_key == 'your_groq_api_key_here':
        print("[ERROR] GROQ API key is required for the language model!")
        return False

    # Write to .env file
    try:
        with open(env_file, 'w') as f:
            f.write("# Teaching Assistant API Keys\n")
            f.write("# Generated by setup_api_keys.py\n\n")
            f.write(f"OPENAI_API_KEY={openai_key}\n")
            f.write(f"GROQ_API_KEY={groq_key}\n")
            f.write("\n# Additional configuration can be added here\n")

        print()
        print("[SUCCESS] API keys saved successfully!")
        print(f"[CONFIG] Configuration saved to: {os.path.abspath(env_file)}")
        print()
        print("[RUN] You can now run the teaching assistant with: python py_app.py")
        print()
        print("[WARNING] Important: Keep your .env file private and don't share your API keys!")

        return True

    except Exception as e:
        print(f"[ERROR] Error saving API keys: {e}")
        return False

def check_keys():
    """Check if API keys are properly configured"""
    print("[CHECK] Checking API key configuration...")

    # Check environment variables
    openai_key = os.getenv('OPENAI_API_KEY')
    groq_key = os.getenv('GROQ_API_KEY')

    # Check .env file
    env_file = ".env"
    if os.path.exists(env_file):
        print(f"[FOUND] Found {env_file} file")
        try:
            # Try to load from .env file
            with open(env_file, 'r') as f:
                for line in f:
                    if '=' in line and not line.strip().startswith('#'):
                        key, value = line.strip().split('=', 1)
                        if key == 'OPENAI_API_KEY' and not openai_key:
                            openai_key = value
                        elif key == 'GROQ_API_KEY' and not groq_key:
                            groq_key = value
        except Exception as e:
            print(f"Warning: Error reading .env file: {e}")
    else:
        print(f"[WARNING] No {env_file} file found")

    # Report status
    print()
    if openai_key and openai_key != 'your_openai_api_key_here':
        print("[OK] OpenAI API key: Configured")
    else:
        print("[MISSING] OpenAI API key: Not configured")

    if groq_key and groq_key != 'your_groq_api_key_here':
        print("[OK] GROQ API key: Configured")
    else:
        print("[MISSING] GROQ API key: Not configured")

    both_configured = (openai_key and openai_key != 'your_openai_api_key_here' and
                      groq_key and groq_key != 'your_groq_api_key_here')

    print()
    if both_configured:
        print("[SUCCESS] All API keys are properly configured!")
        print("You can run the application with: python py_app.py")
    else:
        print("[WARNING] Some API keys are missing. Run this script to set them up.")

    return both_configured

if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "check":
        check_keys()
    else:
        success = setup_api_keys()
        if success:
            print("[COMPLETE] Setup complete! Your teaching assistant is ready to use.")
        else:
            print("[FAILED] Setup failed. Please try again.")
            sys.exit(1)